<?xml version="1.0" encoding="utf-8"?><Database Name="qlyQuanMuc" Class="qlyQuanMucDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MINH_NHUT;Initial Catalog=qlyQuanMuc;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="LibarySystem.Properties.Settings" SettingsPropertyName="qlyQuanMucConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.list_QuanMuc" Member="list_QuanMucs">
    <Type Name="list_QuanMuc">
      <Column Name="ID" Type="System.String" DbType="NChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ContactNumber" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>