//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibarySystem.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlySach;Integrated Security=True;TrustServe" +
            "rCertificate=True")]
        public string qlySachConnectionString {
            get {
                return ((string)(this["qlySachConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyThanhvien;Integrated Security=True;Trust" +
            "ServerCertificate=True")]
        public string qlyThanhvienConnectionString {
            get {
                return ((string)(this["qlyThanhvienConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyMuon;Integrated Security=True;TrustServe" +
            "rCertificate=True")]
        public string qlyMuonConnectionString {
            get {
                return ((string)(this["qlyMuonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyTaiKhoan;Integrated Security=True;TrustS" +
            "erverCertificate=True")]
        public string qlyTaiKhoanConnectionString {
            get {
                return ((string)(this["qlyTaiKhoanConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyThanhvien;Integrated Security=True;Encry" +
            "pt=True;TrustServerCertificate=True")]
        public string qlyThanhvienConnectionString1 {
            get {
                return ((string)(this["qlyThanhvienConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyTaiKhoan;Integrated Security=True;Encryp" +
            "t=True;TrustServerCertificate=True")]
        public string qlyTaiKhoanConnectionString1 {
            get {
                return ((string)(this["qlyTaiKhoanConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyQuanMuc;Integrated Security=True;TrustSe" +
            "rverCertificate=True")]
        public string qlyQuanMucConnectionString {
            get {
                return ((string)(this["qlyQuanMucConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MINH_NHUT;Initial Catalog=qlyMuon;Integrated Security=True;Encrypt=Tr" +
            "ue;TrustServerCertificate=True")]
        public string qlyMuonConnectionString1 {
            get {
                return ((string)(this["qlyMuonConnectionString1"]));
            }
        }
    }
}
